import Header from "./components/Header";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"] });

export const metadata = {
	title: "Nextjs-13 tutorial",
	description: "Generated by create next app",
	keywords:
		"Web development, web design, javascript, react, node, angular, vue, html, css, bootstrap, sass",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<Header />
				<main className="container">{children}</main>
			</body>
		</html>
	);
}
